title = "Tract"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
font_awesome_version = "5.11.2"
description = "A Hugo theme for ambitious documentation projects"

[params.social.github]
name = "GitHub"
url = "https://github.com/tract-docs/tract-hugo-theme"
color = "black"
icon = "fab fa-github"

[params.social.twitter]
name = "Twitter"
url = "https://twitter.com/lucperkins"
color = "twitter-blue"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Nunito Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"
